[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Full"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
 normal=  {family = "OpenDyslexicM Nerd Font Mono", style = "Regular"}
offset.y=2
size = 12

[keyboard]
bindings = [
  ##  {key = "V", mods = "Control", action = "Paste"}
]

[colors.cursor]

text = "#282a36"
cursor = "#f8f8f2"

[colors.vi_mode_cursor]

text = "CellBackground"
cursor = "CellForeground"

[colors.selection]

text = "CellForeground"
background = "#44475a"

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#9699a8"
yellow = "#e0af68"

[colors.primary]
background = "#24283b"
foreground = "#a9b1d6"
